# Generated by Django 3.1.5 on 2021-01-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20210108_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='note',
            name='mod_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
